base_url = "https://cakehonolulu.github.io"
theme = "kita"

title = "cakehonolulu's blog"
description = "Get the latest language learning news."

author = "cakehonolulu"

compile_sass = true

taxonomies = [{ name = "tags", rss = true, paginate_by = 5 }]

build_search_index = true

default_language = "en"

generate_feeds = true

feed_filenames = ["atom.xml", "rss.xml"]

[markdown]
highlight_code = true

[extra]
math = true
mermaid = true
comment = true

[[extra.menu]]
name = "About"
url = "$BASE_URL/about"

[[extra.menu]]
name = "Projects"
url = "$BASE_URL/projects"

[[extra.menu]]
name = "Blog"
url = "$BASE_URL/blog"

[[extra.menu]]
name = "Archive"
url = "$BASE_URL/archive"

[[extra.menu]]
name = "Tags"
url = "$BASE_URL/tags"

[extra.profile]
name = "cakehonolulu"
bio = "A blog containing my personal rants and findings about software"
avatar_url = "images/profile.jpg"

[[extra.profile.social]]
name = "github"
url = "https://github.com/cakehonolulu"

[[extra.profile.social]]
name = "bluesky"
url = "https://bsky.app/profile/cakehonolulu.bsky.social"

[[extra.profile.social]]
name = "mastodon"
url = "https://mastodon.social/@cakehonolulu"

[[extra.profile.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/joel-bueno-calvache/"

[[extra.profile.social]]
name = "kofi"
url = "https://ko-fi.com/cakehonolulu"

[[extra.profile.social]]
name = "rss"
url = "https://cakehonolulu.github.io/atom.xml"

[extra.footer]
since = 2022
license = "MIT"
license_url = "https://mit-license.org/"
