[book]
authors = ["cakehonolulu"]
language = "en"
src = "src"
title = "PCIem"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
no-section-label = true
additional-js = ["mermaid.min.js", "pciem.js", "mermaid-init.js"]
additional-css = ["src/custom.css"]
